export function buildMockQuestions(quiz) {
  if (quiz?.title === "JEE Physics Sectional Mock Test") {
    return [
      // SECTION A (MCQs – Single Correct) (1 mark each, -0.25 negative)
      {
        id: 1,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Mechanics",
        difficulty: "Easy",
        question: "A particle moves in a circle of radius R with constant speed v. The acceleration is:",
        options: ["v/R", "v²/R", "v²/R²", "Zero"],
        answer: 1,
        explanation: "In uniform circular motion, centripetal acceleration is v²/R.",
      },
      {
        id: 2,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Work-Energy",
        difficulty: "Easy",
        question: "Work done by a conservative force depends on:",
        options: ["Path", "Time", "Initial & final position", "Velocity"],
        answer: 2,
        explanation: "For conservative forces, work depends only on endpoints.",
      },
      {
        id: 3,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Kinematics",
        difficulty: "Easy",
        question: "A body is projected vertically upward. At highest point:",
        options: ["Velocity and acceleration both zero", "Velocity zero, acceleration ≠ 0", "Velocity ≠ 0, acceleration zero", "Both non-zero"],
        answer: 1,
        explanation: "At top, v = 0 but acceleration is g downward (non-zero).",
      },
      {
        id: 4,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Units & Dimensions",
        difficulty: "Easy",
        question: "Dimensional formula of Planck’s constant:",
        options: ["ML²T⁻¹", "ML²T⁻²", "MLT⁻¹", "ML²T"],
        answer: 0,
        explanation: "h has dimensions of angular momentum: energy×time = (ML²T⁻²)×T = ML²T⁻¹.",
      },
      {
        id: 5,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Gravitation",
        difficulty: "Easy",
        question: "Escape velocity depends on:",
        options: ["Mass of body only", "Radius only", "Both mass & radius of planet", "None"],
        answer: 2,
        explanation: "v_e = √(2GM/R), depends on both M and R.",
      },
      {
        id: 6,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Electrostatics",
        difficulty: "Easy",
        question: "Unit of electric field is:",
        options: ["Volt", "Newton", "N/C", "Joule"],
        answer: 2,
        explanation: "E = F/q, so unit is N/C (also V/m).",
      },
      {
        id: 7,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "SHM",
        difficulty: "Easy",
        question: "In SHM, maximum velocity occurs at:",
        options: ["Mean position", "Extreme position", "Half displacement", "Anywhere"],
        answer: 0,
        explanation: "Speed is maximum at mean position where potential energy is minimum.",
      },
      {
        id: 8,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Magnetism",
        difficulty: "Easy",
        question: "Magnetic field inside a solenoid is:",
        options: ["Zero", "Constant", "Infinite", "Varies randomly"],
        answer: 1,
        explanation: "Inside an ideal solenoid, B is nearly uniform (constant).",
      },
      {
        id: 9,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Gravitation",
        difficulty: "Easy",
        question: "Total energy of a satellite in orbit is:",
        options: ["Positive", "Negative", "Zero", "Infinite"],
        answer: 1,
        explanation: "For bound orbits, total energy E = -GMm/(2r) is negative.",
      },
      {
        id: 10,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Optics",
        difficulty: "Easy",
        question: "Refractive index depends on:",
        options: ["Wavelength", "Temperature", "Nature of medium", "All"],
        answer: 3,
        explanation: "It can depend on wavelength, temperature, and medium.",
      },

      // SECTION B (Numerical Value Type) (2 marks each, no negative)
      {
        id: 11,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Kinematics",
        difficulty: "Easy",
        question: "A car accelerates from rest at 2 m/s². Distance covered in 5 sec = ____ m",
        answerValue: 25,
        explanation: "s = 1/2 a t² = 1/2 × 2 × 5² = 25 m.",
      },
      {
        id: 12,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "SHM",
        difficulty: "Easy",
        question: "Force required to stretch a spring by 0.1 m if k = 200 N/m = ____ N",
        answerValue: 20,
        explanation: "F = kx = 200 × 0.1 = 20 N.",
      },
      {
        id: 13,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Oscillations",
        difficulty: "Easy",
        question: "Time period of pendulum (l = 1 m, g = 10 m/s²) = ____ sec",
        answerValue: 2,
        explanation: "T = 2π√(l/g) = 2π√(1/10) ≈ 1.99 ≈ 2 s.",
      },
      {
        id: 14,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Current Electricity",
        difficulty: "Easy",
        question: "Charge passing through a conductor in 2 sec with current 3A = ____ C",
        answerValue: 6,
        explanation: "Q = It = 3 × 2 = 6 C.",
      },
      {
        id: 15,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Work-Energy",
        difficulty: "Easy",
        question: "Kinetic energy of 2 kg body moving at 3 m/s = ____ J",
        answerValue: 9,
        explanation: "KE = 1/2 mv² = 1/2 × 2 × 3² = 9 J.",
      },

      // SECTION C (MCQs – Multiple Correct) (4 marks each, -1 negative)
      {
        id: 16,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Vectors",
        difficulty: "Easy",
        question: "Which of the following are vectors?",
        options: ["Velocity", "Work", "Force", "Acceleration"],
        answerIndices: [0, 2, 3],
        explanation: "Velocity, force, and acceleration are vectors; work is scalar.",
      },
      {
        id: 17,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Circular Motion",
        difficulty: "Easy",
        question: "In uniform circular motion:",
        options: ["Speed constant", "Velocity constant", "Acceleration towards center", "Force zero"],
        answerIndices: [0, 2],
        explanation: "Speed is constant but velocity changes direction; acceleration is towards center.",
      },
      {
        id: 18,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Current Electricity",
        difficulty: "Easy",
        question: "Ohm’s law is valid for:",
        options: ["Metals", "Semiconductors", "Constant temperature", "High voltage always"],
        answerIndices: [0, 2],
        explanation: "Ohm's law holds for ohmic conductors (metals) under constant temperature.",
      },
      {
        id: 19,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Waves",
        difficulty: "Easy",
        question: "For a wave:",
        options: ["v = fλ", "Frequency constant", "Wavelength changes with medium", "Speed always constant"],
        answerIndices: [0, 1, 2],
        explanation: "v = fλ; frequency set by source remains same; λ changes with medium; speed changes with medium.",
      },
      {
        id: 20,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "SHM",
        difficulty: "Easy",
        question: "Energy in SHM depends on:",
        options: ["Amplitude", "Mass", "Frequency", "Displacement"],
        answerIndices: [0, 1, 2],
        explanation: "Total energy E = 1/2 m ω² A² depends on m, ω (frequency), and A; not on instantaneous displacement.",
      },
    ];
  }

  if (quiz?.title === "JEE Chemistry Sectional Mock Test") {
    return [
      // SECTION A (MCQs – Single Correct) (1 mark each, -0.25 negative)
      {
        id: 1,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Mole Concept",
        difficulty: "Easy",
        question: "Number of moles in 44 g of CO₂:",
        options: ["0.5", "1", "2", "44"],
        answer: 1,
        explanation: "Moles = mass / molar mass = 44/44 = 1.",
      },
      {
        id: 2,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Ionic Equilibrium",
        difficulty: "Easy",
        question: "The pH of a neutral solution at 25°C is:",
        options: ["0", "7", "14", "1"],
        answer: 1,
        explanation: "Neutral water at 25°C has pH = 7.",
      },
      {
        id: 3,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Periodic Trends",
        difficulty: "Easy",
        question: "Which has maximum electronegativity?",
        options: ["Cl", "F", "O", "N"],
        answer: 1,
        explanation: "Fluorine is the most electronegative element.",
      },
      {
        id: 4,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Chemical Bonding",
        difficulty: "Easy",
        question: "Hybridization of carbon in methane (CH₄):",
        options: ["sp", "sp²", "sp³", "dsp²"],
        answer: 2,
        explanation: "CH₄ has tetrahedral geometry; carbon is sp³ hybridized.",
      },
      {
        id: 5,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Electrochemistry",
        difficulty: "Easy",
        question: "Which is a strong electrolyte?",
        options: ["CH₃COOH", "NaCl", "NH₄OH", "H₂O"],
        answer: 1,
        explanation: "NaCl dissociates completely in water (strong electrolyte).",
      },
      {
        id: 6,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Chemical Kinetics",
        difficulty: "Easy",
        question: "Rate of reaction depends on:",
        options: ["Temperature", "Concentration", "Catalyst", "All"],
        answer: 3,
        explanation: "Rate depends on multiple factors including temperature, concentration, and catalysts.",
      },
      {
        id: 7,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Organic Chemistry",
        difficulty: "Easy",
        question: "Which is aromatic?",
        options: ["Benzene", "Cyclohexane", "Ethane", "Propene"],
        answer: 0,
        explanation: "Benzene is aromatic (6 π-electrons, planar ring).",
      },
      {
        id: 8,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Redox",
        difficulty: "Easy",
        question: "Oxidation state of sulfur in H₂SO₄:",
        options: ["+2", "+4", "+6", "-2"],
        answer: 2,
        explanation: "For H₂SO₄: 2(+1) + S + 4(-2) = 0 ⇒ S = +6.",
      },
      {
        id: 9,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Gas Laws",
        difficulty: "Easy",
        question: "Boyle’s Law relates:",
        options: ["P & V", "V & T", "P & T", "n & T"],
        answer: 0,
        explanation: "Boyle’s law: P ∝ 1/V at constant temperature.",
      },
      {
        id: 10,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Redox",
        difficulty: "Easy",
        question: "Which is a reducing agent?",
        options: ["O₂", "H₂", "Cl₂", "NO₂"],
        answer: 1,
        explanation: "H₂ donates electrons in many reactions, acting as a reducing agent.",
      },

      // SECTION B (Numerical Value Type) (2 marks each, no negative)
      {
        id: 11,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Solutions",
        difficulty: "Easy",
        question: "Molarity of solution with 1 mole solute in 1 L = ____",
        answerValue: 1,
        explanation: "M = moles / volume(L) = 1/1 = 1 M.",
      },
      {
        id: 12,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Mole Concept",
        difficulty: "Easy",
        question: "Number of atoms in 1 mole of helium = ____ × 10²³",
        answerValue: 6.022,
        explanation: "1 mole contains Avogadro's number = 6.022 × 10²³ atoms.",
      },
      {
        id: 13,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Ionic Equilibrium",
        difficulty: "Easy",
        question: "If pH = 3, [H⁺] = ____ mol/L",
        answerValue: 1e-3,
        explanation: "[H⁺] = 10^(-pH) = 10^-3 mol/L.",
      },
      {
        id: 14,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Thermochemistry",
        difficulty: "Easy",
        question:
          "Heat required to raise temp of 1 kg water by 1°C (specific heat = 4200 J/kg·K) = ____ J",
        answerValue: 4200,
        explanation: "Q = mcΔT = 1 × 4200 × 1 = 4200 J.",
      },
      {
        id: 15,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Gas Laws",
        difficulty: "Easy",
        question: "Volume of 1 mole gas at STP = ____ L",
        answerValue: 22.4,
        explanation: "Molar volume at STP ≈ 22.4 L/mol.",
      },

      // SECTION C (MCQs – Multiple Correct) (4 marks each, -1 negative)
      {
        id: 16,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Thermodynamics",
        difficulty: "Easy",
        question: "Which are state functions?",
        options: ["Enthalpy", "Work", "Internal energy", "Heat"],
        answerIndices: [0, 2],
        explanation: "Enthalpy and internal energy are state functions; work and heat are path functions.",
      },
      {
        id: 17,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Chemical Kinetics",
        difficulty: "Easy",
        question: "Which factors affect rate of reaction?",
        options: ["Temperature", "Catalyst", "Surface area", "Pressure"],
        answerIndices: [0, 1, 2, 3],
        explanation: "All listed factors can affect reaction rate (pressure mainly for gases).",
      },
      {
        id: 18,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Solutions",
        difficulty: "Easy",
        question: "Which are colligative properties?",
        options: ["Osmotic pressure", "Boiling point elevation", "Density", "Freezing point depression"],
        answerIndices: [0, 1, 3],
        explanation:
          "Colligative properties depend on number of solute particles: osmotic pressure, ΔTb, ΔTf (not density).",
      },
      {
        id: 19,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Chemical Bonding",
        difficulty: "Easy",
        question: "Which compounds show resonance?",
        options: ["Benzene", "NO₃⁻", "CO₂", "O₃"],
        answerIndices: [0, 1, 3],
        explanation: "Benzene, nitrate, and ozone have resonance structures; CO₂ is typically represented with two double bonds.",
      },
      {
        id: 20,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Organic Chemistry",
        difficulty: "Easy",
        question: "Which are nucleophiles?",
        options: ["OH⁻", "NH₃", "BF₃", "CN⁻"],
        answerIndices: [0, 1, 3],
        explanation: "Nucleophiles donate electron pairs (OH⁻, NH₃, CN⁻). BF₃ is an electrophile (Lewis acid).",
      },
    ];
  }

  if (quiz?.title === "JEE Mathematics Sectional Mock Test") {
    return [
      // SECTION A (MCQs – Single Correct) (1 mark each, -0.25 negative)
      {
        id: 1,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Quadratic Equations",
        difficulty: "Easy",
        question: "If (x^2 - 5x + 6 = 0), then the roots are:",
        options: ["1, 6", "2, 3", "-2, -3", "0, 6"],
        answer: 1,
        explanation: "x^2 - 5x + 6 = (x-2)(x-3) so roots are 2 and 3.",
      },
      {
        id: 2,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Trigonometry",
        difficulty: "Easy",
        question: "Value of (sin^2θ + cos^2θ) is:",
        options: ["0", "1", "2", "Depends on θ"],
        answer: 1,
        explanation: "Identity: sin^2θ + cos^2θ = 1 for all θ.",
      },
      {
        id: 3,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Coordinate Geometry",
        difficulty: "Easy",
        question: "The slope of line (y = 3x + 2) is:",
        options: ["2", "3", "1", "0"],
        answer: 1,
        explanation: "In y = mx + c, slope is m = 3.",
      },
      {
        id: 4,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Logarithms",
        difficulty: "Easy",
        question: "If (log10 100 = x), then x =",
        options: ["1", "2", "10", "100"],
        answer: 1,
        explanation: "log10(100) = 2 because 10^2 = 100.",
      },
      {
        id: 5,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Differentiation",
        difficulty: "Easy",
        question: "Derivative of (x^2) is:",
        options: ["x", "2x", "x²", "2"],
        answer: 1,
        explanation: "d/dx (x^2) = 2x.",
      },
      {
        id: 6,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Quadratic Equations",
        difficulty: "Easy",
        question: "If (a + b = 10), (ab = 21), then values of a, b are:",
        options: ["3, 7", "2, 8", "1, 9", "5, 5"],
        answer: 0,
        explanation: "Numbers with sum 10 and product 21 are 3 and 7.",
      },
      {
        id: 7,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Circles",
        difficulty: "Easy",
        question: "Equation of a circle with center (0,0) and radius 5:",
        options: ["x² + y² = 5", "x² + y² = 25", "x + y = 5", "x² − y² = 25"],
        answer: 1,
        explanation: "Center at origin: x² + y² = r² = 25.",
      },
      {
        id: 8,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Trigonometry",
        difficulty: "Easy",
        question: "Value of (tan 45°):",
        options: ["0", "1", "√3", "Undefined"],
        answer: 1,
        explanation: "tan 45° = 1.",
      },
      {
        id: 9,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Permutations",
        difficulty: "Easy",
        question: "Number of permutations of 3 objects from 5 =",
        options: ["60", "20", "120", "10"],
        answer: 0,
        explanation: "5P3 = 5×4×3 = 60.",
      },
      {
        id: 10,
        section: "A",
        type: "single",
        marks: 1,
        negative: 0.25,
        topic: "Integration",
        difficulty: "Easy",
        question: "Integral of (1 dx) is:",
        options: ["x", "1", "x²", "0"],
        answer: 0,
        explanation: "∫1 dx = x + C.",
      },

      // SECTION B (Numerical Value Type) (2 marks each, no negative)
      {
        id: 11,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Exponents",
        difficulty: "Easy",
        question: "Value of (2^5 = ____ )",
        answerValue: 32,
        explanation: "2^5 = 32.",
      },
      {
        id: 12,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Determinants",
        difficulty: "Easy",
        question: "Determinant of matrix |1 2; 3 4| = ____",
        answerValue: -2,
        explanation: "Det = 1×4 − 2×3 = 4 − 6 = −2.",
      },
      {
        id: 13,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Coordinate Geometry",
        difficulty: "Easy",
        question: "Distance between points (0,0) and (3,4) = ____",
        answerValue: 5,
        explanation: "Distance = √(3^2 + 4^2) = 5.",
      },
      {
        id: 14,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Numbers",
        difficulty: "Easy",
        question: "Value of (√81 = ____ )",
        answerValue: 9,
        explanation: "√81 = 9.",
      },
      {
        id: 15,
        section: "B",
        type: "numerical",
        marks: 2,
        negative: 0,
        topic: "Linear Equations",
        difficulty: "Easy",
        question: "If (x + 2 = 5), then x = ____",
        answerValue: 3,
        explanation: "x = 5 − 2 = 3.",
      },

      // SECTION C (MCQs – Multiple Correct) (4 marks each, -1 negative)
      {
        id: 16,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Quadratic Equations",
        difficulty: "Easy",
        question: "Which are solutions of (x^2 = 4)?",
        options: ["2", "-2", "4", "-4"],
        answerIndices: [0, 1],
        explanation: "x^2 = 4 ⇒ x = ±2.",
      },
      {
        id: 17,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Functions",
        difficulty: "Easy",
        question: "Which functions are continuous everywhere?",
        options: ["x^2", "sin x", "1/x", "e^x"],
        answerIndices: [0, 1, 3],
        explanation: "Polynomials, sin x, and e^x are continuous everywhere; 1/x is not at x=0.",
      },
      {
        id: 18,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Trigonometry",
        difficulty: "Easy",
        question: "Which are identities?",
        options: [
          "sin^2θ + cos^2θ = 1",
          "1 + tan^2θ = sec^2θ",
          "sinθ = cosθ",
          "cot^2θ + 1 = csc^2θ",
        ],
        answerIndices: [0, 1, 3],
        explanation: "Standard identities: (A), (B), (D) are true; (C) only for specific θ.",
      },
      {
        id: 19,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Straight Lines",
        difficulty: "Easy",
        question: "Which represent straight lines?",
        options: ["y = 2x + 1", "x + y = 0", "x² + y² = 1", "y = constant"],
        answerIndices: [0, 1, 3],
        explanation: "Linear equations and y=constant are lines; x² + y² = 1 is a circle.",
      },
      {
        id: 20,
        section: "C",
        type: "multi",
        marks: 4,
        negative: 1,
        topic: "Monotonicity",
        difficulty: "Easy",
        question: "Which are increasing functions?",
        options: ["x^2", "e^x", "ln x", "-x"],
        answerIndices: [1, 2],
        explanation: "e^x increases for all x; ln x increases for x>0; -x decreases; x^2 not increasing on all ℝ.",
      },
    ];
  }

  if (quiz?.title === "CDS / NDA Mathematics Sectional Mock Test") {
    const mk = (id, question, options, answer, topic = "Mathematics") => ({
      id,
      section: "A",
      type: "single",
      marks: 1,
      negative: 0.33,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per CDS / NDA mathematics sectional key.",
    });

    return [
      mk(1, "Simplify: (2 + 3 x 4)", ["20", "14", "24", "18"], 1, "Arithmetic"),
      mk(2, "Find HCF of 12 and 18:", ["2", "3", "6", "12"], 2, "Number System"),
      mk(3, "25% of 200 =", ["25", "50", "75", "100"], 1, "Percentages"),
      mk(4, "If x + 5 = 10, then x =", ["5", "10", "15", "0"], 0, "Algebra"),
      mk(5, "Simplify: (3/4 + 1/4)", ["1", "1/2", "3/8", "4/8"], 0, "Fractions"),
      mk(6, "Square of 12 =", ["124", "144", "122", "142"], 1, "Numbers"),
      mk(7, "Cube of 3 =", ["9", "27", "6", "18"], 1, "Numbers"),
      mk(8, "sqrt(49) =", ["6", "7", "8", "9"], 1, "Numbers"),
      mk(9, "If 2x = 10, x =", ["2", "3", "5", "10"], 2, "Algebra"),
      mk(10, "LCM of 4 and 6 =", ["12", "24", "6", "18"], 0, "Number System"),
      mk(11, "Ratio 2:3 =", ["2/3", "3/2", "5/6", "1/2"], 0, "Ratio"),
      mk(12, "Simple interest on Rs.1000 at 10% for 1 year =", ["100", "200", "50", "150"], 0, "Simple Interest"),
      mk(13, "Average of 2, 4, 6 =", ["3", "4", "5", "6"], 1, "Average"),
      mk(14, "Speed = distance/time. If d = 60 km, t = 2 h:", ["30", "60", "120", "20"], 0, "Speed Time Distance"),
      mk(15, "Angle sum of triangle =", ["90 deg", "180 deg", "360 deg", "270 deg"], 1, "Geometry"),
      mk(16, "Area of square (side 4 cm) =", ["8", "16", "12", "20"], 1, "Mensuration"),
      mk(17, "Perimeter of rectangle (l = 5, b = 3) =", ["16", "15", "8", "10"], 0, "Mensuration"),
      mk(18, "sin 30 deg =", ["1", "1/2", "sqrt(3)/2", "0"], 1, "Trigonometry"),
      mk(19, "cos 0 deg =", ["0", "1", "-1", "1/2"], 1, "Trigonometry"),
      mk(20, "tan 45 deg =", ["0", "1", "sqrt(3)", "Undefined"], 1, "Trigonometry"),
      mk(21, "If a^2 = 16, a =", ["4", "-4", "+/-4", "8"], 2, "Algebra"),
      mk(22, "Linear equation:", ["x^2 + 1", "x + 2", "x^3", "1/x"], 1, "Algebra"),
      mk(23, "Probability always lies between:", ["-1 to 1", "0 to 1", "1 to 2", "0 to 2"], 1, "Probability"),
      mk(24, "Number of outcomes when tossing a coin =", ["1", "2", "3", "4"], 1, "Probability"),
      mk(25, "Median of 1, 3, 5 =", ["1", "3", "5", "9"], 1, "Statistics"),
      mk(26, "Mode is:", ["Highest value", "Most frequent", "Average", "Middle"], 1, "Statistics"),
      mk(27, "Area of triangle =", ["bh", "1/2 bh", "b+h", "b^2"], 1, "Mensuration"),
      mk(28, "Volume of cube (side a) =", ["a^2", "a^3", "2a", "a/3"], 1, "Mensuration"),
      mk(29, "Surface area of cube =", ["6a^2", "a^2", "a^3", "4a^2"], 0, "Mensuration"),
      mk(30, "If 5x = 25, x =", ["5", "10", "25", "1"], 0, "Algebra"),
      mk(31, "sqrt(16 + 9) =", ["5", "25", "7", "3"], 0, "Numbers"),
      mk(32, "If x = 2, value of x^2 =", ["2", "4", "8", "6"], 1, "Algebra"),
      mk(33, "Complementary angles sum =", ["180 deg", "90 deg", "360 deg", "45 deg"], 1, "Geometry"),
      mk(34, "Supplementary angles sum =", ["90 deg", "180 deg", "360 deg", "270 deg"], 1, "Geometry"),
      mk(35, "sin^2 theta + cos^2 theta =", ["0", "1", "2", "theta"], 1, "Trigonometry"),
      mk(36, "If 10% of x = 5, x =", ["50", "5", "10", "100"], 0, "Percentages"),
      mk(37, "3^2 + 4^2 =", ["7", "25", "12", "9"], 1, "Numbers"),
      mk(38, "Distance between (0,0) and (3,4) =", ["5", "7", "4", "3"], 0, "Coordinate Geometry"),
      mk(39, "Equation of line:", ["y = mx + c", "x^2 + y^2", "xy", "None"], 0, "Coordinate Geometry"),
      mk(40, "Mean =", ["Sum/n", "n/sum", "product", "difference"], 0, "Statistics"),
      mk(41, "1 km =", ["100 m", "1000 m", "10 m", "10000 m"], 1, "Units"),
      mk(42, "1 hour =", ["30 min", "60 min", "100 min", "120 min"], 1, "Units"),
      mk(43, "Fraction 1/2 in decimal =", ["0.5", "0.2", "2", "1"], 0, "Fractions"),
      mk(44, "If a:b = 2:4, simplified =", ["1:2", "2:1", "4:2", "3:2"], 0, "Ratio"),
      mk(45, "Area of circle =", ["pi r^2", "2pi r", "r^2", "pi d"], 0, "Mensuration"),
      mk(46, "Circumference =", ["2pi r", "pi r^2", "r^2", "pi"], 0, "Mensuration"),
      mk(47, "If 8x = 40, x =", ["5", "8", "4", "10"], 0, "Algebra"),
      mk(48, "Cube root of 27 =", ["3", "9", "6", "2"], 0, "Numbers"),
      mk(49, "Even number example:", ["3", "5", "8", "7"], 2, "Number System"),
      mk(50, "Prime number:", ["4", "6", "7", "9"], 2, "Number System"),
    ];
  }

  if (quiz?.title === "CDS / NDA English Sectional Mock Test") {
    const mk = (id, question, options, answer, topic) => ({
      id,
      section: "A",
      type: "single",
      marks: 1,
      negative: 0.33,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per CDS / NDA English sectional key.",
    });

    return [
      mk(1, "Choose the correct sentence:", ["He don't like coffee.", "He doesn't likes coffee.", "He doesn't like coffee.", "He not like coffee."], 2, "Grammar & Usage"),
      mk(2, "Fill in the blank: She ___ going to school daily.", ["is", "are", "am", "be"], 0, "Grammar & Usage"),
      mk(3, "Identify the error: He have completed his work.", ["He", "have", "completed", "work"], 1, "Grammar & Usage"),
      mk(4, "Choose correct tense: I ___ this book yesterday.", ["read", "reads", "reading", "will read"], 0, "Grammar & Usage"),
      mk(5, "Fill in the blank: They ___ playing football.", ["is", "are", "am", "be"], 1, "Grammar & Usage"),
      mk(6, "Correct passive voice: Ram wrote a letter.", ["A letter was written by Ram.", "A letter is written by Ram.", "A letter written by Ram.", "Ram was written a letter."], 0, "Grammar & Usage"),
      mk(7, "Choose correct preposition: She is fond ___ music.", ["of", "in", "at", "on"], 0, "Grammar & Usage"),
      mk(8, "Fill in the blank: I prefer tea ___ coffee.", ["than", "over", "to", "from"], 2, "Grammar & Usage"),
      mk(9, "Choose correct article: ___ apple a day keeps doctor away.", ["A", "An", "The", "No article"], 1, "Grammar & Usage"),
      mk(10, "Identify correct sentence:", ["She can sings well.", "She can sing well.", "She can singing well.", "She can sung well."], 1, "Grammar & Usage"),
      mk(11, "Fill in the blank: He is afraid ___ dogs.", ["of", "from", "to", "at"], 0, "Grammar & Usage"),
      mk(12, "Choose correct form: She ___ finished her work.", ["have", "has", "had", "having"], 1, "Grammar & Usage"),
      mk(13, "Identify error: Each of the boys are present.", ["Each", "of", "boys", "are"], 3, "Grammar & Usage"),
      mk(14, "Fill in the blank: He works ___ a teacher.", ["as", "like", "for", "by"], 0, "Grammar & Usage"),
      mk(15, "Choose correct sentence:", ["I did not went there.", "I did not go there.", "I not went there.", "I did not gone there."], 1, "Grammar & Usage"),
      mk(16, 'Synonym of "Brave":', ["Coward", "Bold", "Weak", "Fearful"], 1, "Vocabulary"),
      mk(17, 'Antonym of "Hot":', ["Warm", "Cold", "Boiling", "Heat"], 1, "Vocabulary"),
      mk(18, 'Synonym of "Quick":', ["Slow", "Rapid", "Lazy", "Late"], 1, "Vocabulary"),
      mk(19, 'Antonym of "Happy":', ["Joyful", "Sad", "Glad", "Cheerful"], 1, "Vocabulary"),
      mk(20, 'Meaning of "Honest":', ["Truthful", "Liar", "Clever", "Smart"], 0, "Vocabulary"),
      mk(21, 'One word for "One who teaches":', ["Teacher", "Student", "Doctor", "Player"], 0, "Vocabulary"),
      mk(22, 'Synonym of "Big":', ["Small", "Huge", "Tiny", "Short"], 1, "Vocabulary"),
      mk(23, 'Antonym of "Strong":', ["Weak", "Tough", "Solid", "Hard"], 0, "Vocabulary"),
      mk(24, 'Meaning of "Ancient":', ["Modern", "Old", "New", "Young"], 1, "Vocabulary"),
      mk(25, 'Synonym of "Smart":', ["Intelligent", "Foolish", "Weak", "Slow"], 0, "Vocabulary"),
      mk(26, "Passage: Education is the most powerful weapon... What is education called?", ["Weapon", "Tool", "Burden", "Game"], 0, "Comprehension"),
      mk(27, "Passage-based: Education helps in:", ["Destruction", "Growth", "Ignorance", "Laziness"], 1, "Comprehension"),
      mk(28, "Passage-based: It improves:", ["Society", "Only individuals", "Only schools", "Nothing"], 0, "Comprehension"),
      mk(29, "Passage-based: Education develops:", ["Skills", "Weakness", "Fear", "Anger"], 0, "Comprehension"),
      mk(30, "Passage-based: Passage tone is:", ["Negative", "Positive", "Neutral", "Angry"], 1, "Comprehension"),
      mk(31, "Choose correct spelling:", ["Recieve", "Receive", "Recive", "Receeve"], 1, "Sentence Improvement & Misc."),
      mk(32, "Fill in: He is ___ than me.", ["taller", "tall", "tallest", "more tall"], 0, "Sentence Improvement & Misc."),
      mk(33, "Correct sentence:", ["She don't know.", "She doesn't know.", "She not know.", "She no know."], 1, "Sentence Improvement & Misc."),
      mk(34, "Choose correct word: I will meet you ___ Monday.", ["in", "on", "at", "by"], 1, "Sentence Improvement & Misc."),
      mk(35, "Identify correct sentence:", ["He has ate food.", "He has eaten food.", "He have eaten food.", "He had ate food."], 1, "Sentence Improvement & Misc."),
      mk(36, "Choose correct option: They ___ finished the work.", ["has", "have", "had", "having"], 1, "Sentence Improvement & Misc."),
      mk(37, "Fill in: She is good ___ English.", ["in", "at", "on", "for"], 1, "Sentence Improvement & Misc."),
      mk(38, "Choose correct form: He ___ to school daily.", ["go", "goes", "going", "gone"], 1, "Sentence Improvement & Misc."),
      mk(39, "Identify correct article: ___ sun rises in east.", ["A", "An", "The", "No article"], 2, "Sentence Improvement & Misc."),
      mk(40, "Choose correct: I have ___ my homework.", ["do", "did", "done", "doing"], 2, "Sentence Improvement & Misc."),
      mk(41, 'One word substitution: "A place where books are kept"', ["Library", "School", "Office", "Shop"], 0, "Sentence Improvement & Misc."),
      mk(42, 'Synonym of "Calm":', ["Angry", "Peaceful", "Loud", "Rough"], 1, "Sentence Improvement & Misc."),
      mk(43, 'Antonym of "Fast":', ["Quick", "Rapid", "Slow", "Speed"], 2, "Sentence Improvement & Misc."),
      mk(44, "Fill in: He is fond ___ cricket.", ["of", "in", "at", "on"], 0, "Sentence Improvement & Misc."),
      mk(45, "Choose correct: She ___ a song now.", ["sing", "sings", "is singing", "sang"], 2, "Sentence Improvement & Misc."),
      mk(46, "Correct sentence:", ["I am agree.", "I agree.", "I am agreed.", "I agreeing."], 1, "Sentence Improvement & Misc."),
      mk(47, "Fill in: He lives ___ Mumbai.", ["in", "on", "at", "by"], 0, "Sentence Improvement & Misc."),
      mk(48, "Choose correct: We ___ playing.", ["is", "are", "am", "be"], 1, "Sentence Improvement & Misc."),
      mk(49, 'Synonym of "Easy":', ["Hard", "Simple", "Tough", "Complex"], 1, "Sentence Improvement & Misc."),
      mk(50, 'Antonym of "Early":', ["Soon", "Late", "Quick", "Fast"], 1, "Sentence Improvement & Misc."),
    ];
  }

  if (quiz?.title === "CDS / NDA GK Sectional Mock Test") {
    const mk = (id, question, options, answer, topic) => ({
      id,
      section: "A",
      type: "single",
      marks: 1,
      negative: 0.33,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per CDS / NDA GK sectional key.",
    });

    return [
      mk(1, "Who was the first Governor-General of independent India?", ["Lord Mountbatten", "C. Rajagopalachari", "Jawaharlal Nehru", "Sardar Patel"], 0, "History"),
      mk(2, "The Revolt of 1857 started at:", ["Delhi", "Meerut", "Kanpur", "Lucknow"], 1, "History"),
      mk(3, "Who founded the Maurya Empire?", ["Ashoka", "Chandragupta Maurya", "Bindusara", "Harsha"], 1, "History"),
      mk(4, 'Who was known as "Iron Man of India"?', ["Nehru", "Gandhi", "Sardar Patel", "Bose"], 2, "History"),
      mk(5, "Jallianwala Bagh massacre took place in:", ["1915", "1919", "1920", "1930"], 1, "History"),
      mk(6, "The Constitution of India came into force on:", ["15 Aug 1947", "26 Jan 1950", "2 Oct 1947", "1 Jan 1950"], 1, "Polity"),
      mk(7, "Fundamental Rights are in:", ["Part II", "Part III", "Part IV", "Part V"], 1, "Polity"),
      mk(8, "Who is the head of the State in India?", ["Prime Minister", "President", "Chief Justice", "Governor"], 1, "Polity"),
      mk(9, "Lok Sabha members are elected for:", ["4 years", "5 years", "6 years", "3 years"], 1, "Polity"),
      mk(10, "Right to vote is:", ["Fundamental Right", "Legal Right", "Natural Right", "None"], 1, "Polity"),
      mk(11, "Largest continent:", ["Africa", "Asia", "Europe", "Australia"], 1, "Geography"),
      mk(12, "Longest river in India:", ["Yamuna", "Ganga", "Brahmaputra", "Godavari"], 1, "Geography"),
      mk(13, "Tropic of Cancer passes through:", ["Middle of India", "North India", "South India", "None"], 0, "Geography"),
      mk(14, "Desert in India:", ["Sahara", "Thar", "Gobi", "Kalahari"], 1, "Geography"),
      mk(15, "Capital of Maharashtra:", ["Pune", "Mumbai", "Nagpur", "Nashik"], 1, "Geography"),
      mk(16, "RBI stands for:", ["Reserve Bank of India", "Rural Bank of India", "Regional Bank of India", "None"], 0, "Economy"),
      mk(17, "GDP means:", ["Gross Domestic Product", "Gross Development Plan", "General Domestic Product", "None"], 0, "Economy"),
      mk(18, "Inflation means:", ["Price rise", "Price fall", "Stability", "None"], 0, "Economy"),
      mk(19, "Currency of India:", ["Dollar", "Rupee", "Pound", "Yen"], 1, "Economy"),
      mk(20, "Budget is presented by:", ["President", "Prime Minister", "Finance Minister", "RBI Governor"], 2, "Economy"),
      mk(21, "Unit of force:", ["Joule", "Newton", "Watt", "Pascal"], 1, "Science"),
      mk(22, "H2O is:", ["Hydrogen", "Oxygen", "Water", "Acid"], 2, "Science"),
      mk(23, "Earth revolves around:", ["Moon", "Sun", "Mars", "Venus"], 1, "Science"),
      mk(24, "Vitamin C deficiency causes:", ["Rickets", "Scurvy", "Night blindness", "Beriberi"], 1, "Science"),
      mk(25, "Human heart has:", ["2 chambers", "3 chambers", "4 chambers", "5 chambers"], 2, "Science"),
      mk(26, "National animal of India:", ["Lion", "Tiger", "Elephant", "Peacock"], 1, "Current Affairs / Static GK"),
      mk(27, "National bird of India:", ["Peacock", "Sparrow", "Crow", "Eagle"], 0, "Current Affairs / Static GK"),
      mk(28, "ISRO headquarters is in:", ["Mumbai", "Delhi", "Bengaluru", "Chennai"], 2, "Current Affairs / Static GK"),
      mk(29, "Olympics held every:", ["2 years", "3 years", "4 years", "5 years"], 2, "Current Affairs / Static GK"),
      mk(30, "Currency of USA:", ["Euro", "Dollar", "Yen", "Pound"], 1, "Current Affairs / Static GK"),
      mk(31, "Largest ocean:", ["Atlantic", "Pacific", "Indian", "Arctic"], 1, "Mixed GK"),
      mk(32, "First President of India:", ["Rajendra Prasad", "Nehru", "Gandhi", "Patel"], 0, "Mixed GK"),
      mk(33, "Green Revolution related to:", ["Industry", "Agriculture", "Transport", "Education"], 1, "Mixed GK"),
      mk(34, "Red Planet:", ["Earth", "Mars", "Venus", "Jupiter"], 1, "Mixed GK"),
      mk(35, "Largest democracy:", ["USA", "India", "China", "UK"], 1, "Mixed GK"),
      mk(36, "UNO headquarters:", ["London", "Paris", "New York", "Geneva"], 2, "Mixed GK"),
      mk(37, "Currency of Japan:", ["Yuan", "Yen", "Won", "Dollar"], 1, "Mixed GK"),
      mk(38, "First man on Moon:", ["Yuri Gagarin", "Neil Armstrong", "Rakesh Sharma", "Buzz Aldrin"], 1, "Mixed GK"),
      mk(39, "Largest state (area):", ["Maharashtra", "Rajasthan", "UP", "MP"], 1, "Mixed GK"),
      mk(40, "Smallest state:", ["Goa", "Sikkim", "Tripura", "Manipur"], 0, "Mixed GK"),
      mk(41, "National sport (commonly accepted):", ["Cricket", "Hockey", "Football", "Kabaddi"], 1, "Mixed GK"),
      mk(42, "Gateway of India is in:", ["Delhi", "Mumbai", "Kolkata", "Chennai"], 1, "Mixed GK"),
      mk(43, "Capital of USA:", ["New York", "Washington DC", "Los Angeles", "Chicago"], 1, "Mixed GK"),
      mk(44, "Ganga originates from:", ["Yamunotri", "Gangotri", "Kedarnath", "Badrinath"], 1, "Mixed GK"),
      mk(45, "Largest planet:", ["Earth", "Mars", "Jupiter", "Saturn"], 2, "Mixed GK"),
      mk(46, "Currency of UK:", ["Euro", "Pound", "Dollar", "Yen"], 1, "Mixed GK"),
      mk(47, "Indian Parliament consists of:", ["Lok Sabha only", "Rajya Sabha only", "Both Houses", "President only"], 2, "Mixed GK"),
      mk(48, "First Prime Minister of India:", ["Gandhi", "Nehru", "Patel", "Bose"], 1, "Mixed GK"),
      mk(49, "Taj Mahal is in:", ["Delhi", "Agra", "Jaipur", "Lucknow"], 1, "Mixed GK"),
      mk(50, "National flag colors:", ["2", "3", "4", "5"], 1, "Mixed GK"),
    ];
  }

  if (quiz?.title === "NEET Physics Sectional Mock Test") {
    const mk = (id, section, question, options, answer, topic) => ({
      id,
      section,
      type: "single",
      marks: 4,
      negative: 1,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per NEET sectional key.",
    });

    return [
      // SECTION A (35 Questions – Attempt ALL)
      mk(1, "A", "Dimensional formula of force:", ["MLT⁻¹", "MLT⁻²", "ML²T⁻²", "M²LT⁻²"], 1, "Units & Dimensions"),
      mk(2, "A", "Velocity-time graph slope gives:", ["Distance", "Displacement", "Acceleration", "Speed"], 2, "Kinematics"),
      mk(3, "A", "Unit of work is:", ["Watt", "Joule", "Newton", "Pascal"], 1, "Work-Energy"),
      mk(
        4,
        "A",
        "A body of mass 2 kg moving with velocity 3 m/s has momentum:",
        ["6 kg·m/s", "3 kg·m/s", "5 kg·m/s", "1 kg·m/s"],
        0,
        "Momentum",
      ),
      mk(5, "A", "Work done in circular motion is:", ["Maximum", "Minimum", "Zero", "Infinite"], 2, "Circular Motion"),
      mk(6, "A", "Gravitational force is:", ["Repulsive", "Attractive", "Both", "None"], 1, "Gravitation"),
      mk(7, "A", "Escape velocity depends on:", ["Mass of planet", "Radius of planet", "Both", "Neither"], 2, "Gravitation"),
      mk(8, "A", "Unit of electric current:", ["Volt", "Ohm", "Ampere", "Coulomb"], 2, "Current Electricity"),
      mk(9, "A", "Ohm’s law:", ["V = IR", "V = I/R", "V = R/I", "V = IR²"], 0, "Current Electricity"),
      mk(10, "A", "Resistance of conductor depends on:", ["Length", "Area", "Material", "All"], 3, "Current Electricity"),
      mk(
        11,
        "A",
        "Magnetic field due to current is given by:",
        ["Faraday’s law", "Ampere’s law", "Ohm’s law", "Newton’s law"],
        1,
        "Magnetism",
      ),
      mk(12, "A", "Lens formula:", ["1/f = 1/v + 1/u", "f = uv", "v = u + f", "None"], 0, "Optics"),
      mk(13, "A", "Speed of light in vacuum:", ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁵ m/s", "3×10⁷ m/s"], 0, "Modern Physics"),
      mk(14, "A", "Energy of photon depends on:", ["Frequency", "Speed", "Mass", "Volume"], 0, "Modern Physics"),
      mk(15, "A", "SI unit of capacitance:", ["Farad", "Henry", "Tesla", "Weber"], 0, "Electrostatics"),
      mk(16, "A", "In SHM, restoring force is proportional to:", ["Velocity", "Acceleration", "Displacement", "Time"], 2, "SHM"),
      mk(17, "A", "Kinetic energy depends on:", ["Mass", "Velocity", "Both", "None"], 2, "Work-Energy"),
      mk(18, "A", "Unit of frequency:", ["Hz", "m/s", "s", "N"], 0, "Waves"),
      mk(19, "A", "Which is scalar?", ["Velocity", "Force", "Energy", "Momentum"], 2, "Basics"),
      mk(20, "A", "Power =", ["Work × time", "Work/time", "Force × distance", "None"], 1, "Power"),
      mk(21, "A", "Transformer works on:", ["DC", "AC", "Both", "None"], 1, "EMI"),
      mk(22, "A", "Photoelectric effect proves:", ["Wave nature", "Particle nature", "Both", "None"], 1, "Modern Physics"),
      mk(23, "A", "Heat flows from:", ["Low to high temp", "High to low temp", "Both", "None"], 1, "Thermal"),
      mk(24, "A", "Unit of pressure:", ["Pascal", "Joule", "Watt", "Newton"], 0, "Thermal"),
      mk(25, "A", "Angular momentum is:", ["Scalar", "Vector", "Both", "None"], 1, "Rotational Motion"),
      mk(26, "A", "Doppler effect is related to:", ["Frequency", "Wavelength", "Speed", "All"], 3, "Waves"),
      mk(27, "A", "Current in series circuit:", ["Same", "Different", "Zero", "Infinite"], 0, "Current Electricity"),
      mk(28, "A", "Work-energy theorem relates:", ["Work & energy", "Energy & power", "Power & time", "Force & mass"], 0, "Work-Energy"),
      mk(29, "A", "Unit of magnetic field:", ["Tesla", "Henry", "Farad", "Coulomb"], 0, "Magnetism"),
      mk(30, "A", "Time period of pendulum depends on:", ["Mass", "Length", "Both", "None"], 1, "Oscillations"),
      mk(31, "A", "Nuclear force is:", ["Weak", "Strong", "Gravitational", "Electric"], 1, "Nuclear Physics"),
      mk(32, "A", "Semiconductor has:", ["High resistance", "Low resistance", "Intermediate", "Zero"], 2, "Semiconductors"),
      mk(33, "A", "Refraction occurs due to:", ["Speed change", "Direction change", "Both", "None"], 2, "Optics"),
      mk(34, "A", "Electric field lines are:", ["Closed", "Open", "Circular", "None"], 1, "Electrostatics"),
      mk(35, "A", "Unit of inductance:", ["Henry", "Tesla", "Weber", "Ohm"], 0, "EMI"),

      // SECTION B (15 Questions – Attempt ANY 10)
      mk(36, "B", "Force = mass × acceleration. If m=2kg, a=5m/s², F=?", ["10 N", "5 N", "2 N", "7 N"], 0, "Basics"),
      mk(37, "B", "Work done when force 10N moves body by 2m:", ["5J", "20J", "10J", "2J"], 1, "Work-Energy"),
      mk(38, "B", "Potential difference unit:", ["Volt", "Ampere", "Ohm", "Joule"], 0, "Current Electricity"),
      mk(39, "B", "If velocity doubles, KE becomes:", ["Same", "Double", "Four times", "Half"], 2, "Work-Energy"),
      mk(40, "B", "Frequency of wave 50Hz means:", ["50 cycles/sec", "100 cycles/sec", "25 cycles/sec", "None"], 0, "Waves"),
      mk(41, "B", "Power unit:", ["Watt", "Joule", "Newton", "Pascal"], 0, "Power"),
      mk(42, "B", "Current = charge/time. If Q=10C, t=2s, I=?", ["5A", "10A", "2A", "20A"], 0, "Current Electricity"),
      mk(43, "B", "Speed = distance/time. If d=100m, t=10s:", ["5", "10", "20", "50"], 1, "Kinematics"),
      mk(44, "B", "Resistance formula:", ["V=IR", "R=V/I", "I=VR", "None"], 1, "Current Electricity"),
      mk(45, "B", "Unit of momentum:", ["kg·m/s", "N", "J", "W"], 0, "Momentum"),
      mk(46, "B", "If wavelength increases, frequency:", ["Increases", "Decreases", "Same", "Zero"], 1, "Waves"),
      mk(47, "B", "Acceleration due to gravity ≈", ["9.8", "98", "0.98", "980"], 0, "Gravitation"),
      mk(48, "B", "Capacitor stores:", ["Charge", "Current", "Voltage", "Resistance"], 0, "Electrostatics"),
      mk(49, "B", "Mirror formula relates:", ["u, v, f", "V, I, R", "m, v, a", "None"], 0, "Optics"),
      mk(50, "B", "Light behaves as:", ["Wave", "Particle", "Both", "None"], 2, "Modern Physics"),
    ];
  }

  if (quiz?.title === "NEET Chemistry Sectional Mock Test") {
    const mk = (id, section, question, options, answer, topic) => ({
      id,
      section,
      type: "single",
      marks: 4,
      negative: 1,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per NEET sectional key.",
    });

    return [
      // SECTION A (35 Questions – Attempt ALL)
      mk(1, "A", "Number of moles in 22 g of CO₂:", ["0.5", "1", "2", "22"], 0, "Mole Concept"),
      mk(2, "A", "pH of neutral solution at 25°C:", ["0", "7", "14", "1"], 1, "Ionic Equilibrium"),
      mk(3, "A", "Most electronegative element:", ["Cl", "F", "O", "N"], 1, "Periodic Trends"),
      mk(4, "A", "Hybridization of carbon in ethene (C₂H₄):", ["sp", "sp²", "sp³", "dsp²"], 1, "Chemical Bonding"),
      mk(5, "A", "Strong electrolyte:", ["CH₃COOH", "NaCl", "NH₄OH", "H₂O"], 1, "Electrolytes"),
      mk(6, "A", "Rate of reaction depends on:", ["Temperature", "Concentration", "Catalyst", "All"], 3, "Kinetics"),
      mk(7, "A", "Which is aromatic?", ["Benzene", "Cyclohexane", "Ethane", "Propene"], 0, "Organic"),
      mk(8, "A", "Oxidation state of N in NH₃:", ["-3", "+3", "0", "+5"], 0, "Redox"),
      mk(9, "A", "Boyle’s law relates:", ["P & V", "V & T", "P & T", "n & T"], 0, "Gas Laws"),
      mk(10, "A", "Which is reducing agent?", ["O₂", "H₂", "Cl₂", "NO₂"], 1, "Redox"),
      mk(11, "A", "Avogadro number:", ["6.022×10²³", "6.022×10²²", "6.022×10²⁴", "6.022×10²¹"], 0, "Mole Concept"),
      mk(12, "A", "Unit of molarity:", ["mol/L", "mol/kg", "g/L", "kg/mol"], 0, "Solutions"),
      mk(13, "A", "Which is exothermic?", ["Combustion", "Melting", "Evaporation", "Sublimation"], 0, "Thermochemistry"),
      mk(14, "A", "Electron affinity is highest for:", ["F", "Cl", "O", "N"], 1, "Periodic Trends"),
      mk(15, "A", "Periodic table arranged by:", ["Atomic mass", "Atomic number", "Density", "Volume"], 1, "Periodic Table"),
      mk(16, "A", "Which is a noble gas?", ["He", "O", "N", "Cl"], 0, "Periodic Table"),
      mk(17, "A", "Bond in H₂ is:", ["Ionic", "Covalent", "Metallic", "Hydrogen"], 1, "Chemical Bonding"),
      mk(18, "A", "Which is Lewis acid?", ["NH₃", "H₂O", "BF₃", "OH⁻"], 2, "Acids & Bases"),
      mk(19, "A", "Which is amphoteric?", ["NaOH", "Al₂O₃", "HCl", "KOH"], 1, "Inorganic"),
      mk(20, "A", "Which shows hydrogen bonding?", ["CH₄", "NH₃", "CO₂", "H₂"], 1, "Chemical Bonding"),
      mk(21, "A", "Unit of rate constant (1st order):", ["s⁻¹", "mol/L", "L/mol", "None"], 0, "Kinetics"),
      mk(22, "A", "Which is a buffer solution?", ["HCl + NaCl", "CH₃COOH + CH₃COONa", "NaOH + KOH", "H₂SO₄ + Na₂SO₄"], 1, "Ionic Equilibrium"),
      mk(23, "A", "Colligative property depends on:", ["Nature", "Number of particles", "Temperature only", "Pressure only"], 1, "Solutions"),
      mk(24, "A", "Which is a transition metal?", ["Na", "Fe", "Ca", "K"], 1, "Inorganic"),
      mk(25, "A", "Which is an alkali metal?", ["Mg", "Ca", "Na", "Al"], 2, "Inorganic"),
      mk(26, "A", "Oxidation involves:", ["Gain of electrons", "Loss of electrons", "Gain of protons", "Loss of neutrons"], 1, "Redox"),
      mk(27, "A", "Which is a ketone?", ["CH₃CHO", "CH₃COCH₃", "CH₃COOH", "CH₃OH"], 1, "Organic"),
      mk(28, "A", "Which is an alcohol?", ["CH₃OH", "CH₃CHO", "CH₃COOH", "CH₃CN"], 0, "Organic"),
      mk(29, "A", "Which is an isomer?", ["Same formula, different structure", "Same structure", "Same properties", "None"], 0, "Organic"),
      mk(30, "A", "Which polymer is natural?", ["Nylon", "Rubber", "PVC", "Bakelite"], 1, "Polymers"),
      mk(31, "A", "Which is biodegradable?", ["Plastic", "Paper", "Nylon", "PVC"], 1, "Environmental"),
      mk(32, "A", "Which is a greenhouse gas?", ["CO₂", "O₂", "N₂", "H₂"], 0, "Environmental"),
      mk(33, "A", "Which is hard water cause?", ["Na⁺", "Ca²⁺", "K⁺", "Cl⁻"], 1, "Water Chemistry"),
      mk(34, "A", "Which is ore of iron?", ["Bauxite", "Hematite", "Galena", "Zincite"], 1, "Metallurgy"),
      mk(35, "A", "Which is used in galvanization?", ["Cu", "Zn", "Fe", "Al"], 1, "Metallurgy"),

      // SECTION B (15 Questions – Attempt ANY 10)
      mk(36, "B", "Moles in 11 g CO₂ =", ["0.25", "0.5", "1", "2"], 0, "Mole Concept"),
      mk(37, "B", "pH of acidic solution:", ["<7", "=7", ">7", "14"], 0, "Ionic Equilibrium"),
      mk(38, "B", "1 mole gas volume at STP:", ["22.4 L", "24 L", "20 L", "18 L"], 0, "Gas Laws"),
      mk(39, "B", "Strong acid:", ["HCl", "CH₃COOH", "NH₃", "H₂O"], 0, "Acids & Bases"),
      mk(40, "B", "Catalyst does:", ["Increase rate", "Decrease rate", "No change", "Stop reaction"], 0, "Kinetics"),
      mk(41, "B", "Electron donor:", ["Acid", "Base", "Salt", "Metal"], 1, "Acids & Bases"),
      mk(42, "B", "Ionic bond forms by:", ["Sharing", "Transfer", "Attraction", "None"], 1, "Chemical Bonding"),
      mk(43, "B", "Atomic number =", ["Protons", "Neutrons", "Electrons", "Both A & C"], 3, "Atomic Structure"),
      mk(44, "B", "Which is alkene?", ["C₂H₆", "C₂H₄", "C₂H₂", "CH₄"], 1, "Hydrocarbons"),
      mk(45, "B", "Which is saturated hydrocarbon?", ["Alkene", "Alkyne", "Alkane", "Aromatic"], 2, "Hydrocarbons"),
      mk(46, "B", "Functional group of alcohol:", ["-COOH", "-OH", "-CHO", "-NH₂"], 1, "Organic"),
      mk(47, "B", "Which is basic?", ["NH₃", "HCl", "CO₂", "SO₂"], 0, "Acids & Bases"),
      mk(48, "B", "Which is oxidation?", ["Gain e⁻", "Loss e⁻", "Gain H", "Loss O"], 1, "Redox"),
      mk(49, "B", "Which is electrolyte?", ["Sugar", "NaCl", "Urea", "Glucose"], 1, "Electrolytes"),
      mk(50, "B", "Which is aromatic compound?", ["Benzene", "Ethane", "Propene", "Methane"], 0, "Organic"),
    ];
  }

  if (quiz?.title === "NEET Biology Sectional Mock Test") {
    const mk = (id, section, question, options, answer, topic) => ({
      id,
      section,
      type: "single",
      marks: 4,
      negative: 1,
      topic,
      difficulty: "Easy",
      question,
      options,
      answer,
      explanation: "Answer as per NEET sectional key.",
    });

    return [
      // SECTION A (35 Questions – Attempt ALL)
      mk(1, "A", "The basic unit of life is:", ["Tissue", "Cell", "Organ", "System"], 1, "Cell Biology"),
      mk(2, "A", "DNA is located in:", ["Cytoplasm", "Nucleus", "Ribosome", "Cell wall"], 1, "Cell Biology"),
      mk(3, "A", "Which organelle is called “powerhouse of cell”?", ["Nucleus", "Mitochondria", "Golgi body", "Lysosome"], 1, "Cell Biology"),
      mk(4, "A", "Photosynthesis occurs in:", ["Chloroplast", "Mitochondria", "Ribosome", "Nucleus"], 0, "Plant Physiology"),
      mk(5, "A", "Genetic material in viruses is:", ["DNA only", "RNA only", "DNA or RNA", "Protein"], 2, "Genetics"),
      mk(6, "A", "Blood group determined by:", ["Genes", "Diet", "Age", "Climate"], 0, "Genetics"),
      mk(7, "A", "Which is a prokaryote?", ["Amoeba", "Bacteria", "Fungi", "Algae"], 1, "Microbiology"),
      mk(8, "A", "Enzymes are:", ["Carbohydrates", "Proteins", "Lipids", "Vitamins"], 1, "Biomolecules"),
      mk(9, "A", "Unit of heredity:", ["Gene", "DNA", "Chromosome", "Cell"], 0, "Genetics"),
      mk(10, "A", "Mendel worked on:", ["Wheat", "Pea plant", "Rice", "Maize"], 1, "Genetics"),
      mk(11, "A", "Which hormone regulates growth?", ["Insulin", "Thyroxine", "Growth hormone", "Adrenaline"], 2, "Human Physiology"),
      mk(12, "A", "Oxygen is transported by:", ["Plasma", "Hemoglobin", "Platelets", "WBC"], 1, "Human Physiology"),
      mk(13, "A", "Which is largest organ in human body?", ["Liver", "Skin", "Heart", "Brain"], 1, "Human Physiology"),
      mk(14, "A", "Functional unit of kidney:", ["Neuron", "Nephron", "Alveoli", "Villi"], 1, "Human Physiology"),
      mk(15, "A", "Digestion of protein starts in:", ["Mouth", "Stomach", "Small intestine", "Large intestine"], 1, "Human Physiology"),
      mk(16, "A", "Which vitamin is synthesized in skin?", ["A", "B", "C", "D"], 3, "Human Health"),
      mk(17, "A", "Which is connective tissue?", ["Muscle", "Blood", "Nerve", "Epithelium"], 1, "Tissues"),
      mk(18, "A", "Which organ pumps blood?", ["Brain", "Liver", "Heart", "Kidney"], 2, "Human Physiology"),
      mk(19, "A", "Photosynthesis produces:", ["CO₂", "O₂", "N₂", "CH₄"], 1, "Plant Physiology"),
      mk(20, "A", "Which is autotrophic nutrition?", ["Animals", "Plants", "Fungi", "Bacteria"], 1, "Nutrition"),
      mk(21, "A", "Which is a vector for malaria?", ["Housefly", "Female Anopheles", "Male mosquito", "Cockroach"], 1, "Human Health"),
      mk(22, "A", "AIDS is caused by:", ["Bacteria", "Virus", "Fungus", "Protozoa"], 1, "Human Health"),
      mk(23, "A", "Which is endocrine gland?", ["Salivary", "Thyroid", "Sweat", "Liver"], 1, "Human Physiology"),
      mk(24, "A", "Which blood cells fight infection?", ["RBC", "WBC", "Platelets", "Plasma"], 1, "Human Physiology"),
      mk(25, "A", "Which is non-renewable resource?", ["Solar", "Wind", "Coal", "Water"], 2, "Ecology"),
      mk(26, "A", "Which is biodegradable?", ["Plastic", "Glass", "Paper", "Metal"], 2, "Ecology"),
      mk(27, "A", "Darwin proposed:", ["Mutation theory", "Evolution", "Germ theory", "Cell theory"], 1, "Evolution"),
      mk(
        28,
        "A",
        "Which is homologous organ?",
        ["Wings of bird & insect", "Human hand & whale flipper", "Eye of octopus & human", "None"],
        1,
        "Evolution",
      ),
      mk(29, "A", "Which is vestigial organ?", ["Appendix", "Heart", "Liver", "Brain"], 0, "Evolution"),
      mk(30, "A", "Which cycle includes nitrogen fixation?", ["Carbon", "Nitrogen", "Water", "Oxygen"], 1, "Ecology"),
      mk(31, "A", "Which is carnivore?", ["Cow", "Goat", "Tiger", "Deer"], 2, "Ecology"),
      mk(32, "A", "Which is primary consumer?", ["Plant", "Herbivore", "Carnivore", "Decomposer"], 1, "Ecology"),
      mk(33, "A", "Which is producer?", ["Animal", "Plant", "Fungi", "Bacteria"], 1, "Ecology"),
      mk(34, "A", "Which is greenhouse gas?", ["CO₂", "O₂", "N₂", "H₂"], 0, "Ecology"),
      mk(35, "A", "Which is pollination?", ["Fertilization", "Transfer of pollen", "Germination", "Growth"], 1, "Plant Reproduction"),

      // SECTION B (15 Questions – Attempt ANY 10)
      mk(36, "B", "Number of chromosomes in human:", ["23", "46", "44", "48"], 1, "Genetics"),
      mk(37, "B", "DNA stands for:", ["Deoxyribo nucleic acid", "Ribo nucleic acid", "Amino acid", "Protein"], 0, "Genetics"),
      mk(38, "B", "Blood clotting requires:", ["Iron", "Calcium", "Sodium", "Potassium"], 1, "Human Physiology"),
      mk(39, "B", "Insulin regulates:", ["Protein", "Fat", "Blood sugar", "Oxygen"], 2, "Human Physiology"),
      mk(40, "B", "Which is amphibian?", ["Fish", "Frog", "Snake", "Bird"], 1, "Animal Kingdom"),
      mk(41, "B", "Which organ helps breathing?", ["Heart", "Lungs", "Liver", "Kidney"], 1, "Human Physiology"),
      mk(42, "B", "Which is RNA base?", ["Thymine", "Uracil", "Adenine", "Cytosine"], 1, "Genetics"),
      mk(43, "B", "Which is dicot?", ["Wheat", "Rice", "Pea", "Maize"], 2, "Botany"),
      mk(44, "B", "Which is xylem function?", ["Food transport", "Water transport", "Photosynthesis", "Storage"], 1, "Plant Physiology"),
      mk(45, "B", "Which is phloem function?", ["Water transport", "Food transport", "Respiration", "Growth"], 1, "Plant Physiology"),
      mk(46, "B", "Which is anaerobic respiration?", ["Oxygen used", "No oxygen", "Only plants", "Only animals"], 1, "Cellular Respiration"),
      mk(47, "B", "Which is nitrogen fixing bacteria?", ["Rhizobium", "E. coli", "Lactobacillus", "Streptococcus"], 0, "Microbiology"),
      mk(48, "B", "Which is monocot?", ["Pea", "Bean", "Wheat", "Gram"], 2, "Botany"),
      mk(49, "B", "Which is muscle tissue?", ["Neuron", "Fiber", "Blood", "Skin"], 1, "Tissues"),
      mk(50, "B", "Which is habitat?", ["Food", "Shelter", "Natural home", "Water"], 2, "Ecology"),
    ];
  }

  const seed = `${quiz?.subject || "General"} ${quiz?.topic || "Practice"}`;
  const topicBuckets = ["Quant", "Verbal", "Logic"];
  const difficultyBuckets = ["Easy", "Medium", "Hard"];
  return Array.from({ length: quiz?.question_count || 10 }, (_, i) => ({
    id: i + 1,
    question: `${seed}: Question ${i + 1} - Choose the best answer under exam pressure.`,
    options: [
      "Option A - Concept based",
      "Option B - Numerical approach",
      "Option C - Shortcut trick",
      "Option D - Elimination strategy",
    ],
    answer: i % 4,
    topic: topicBuckets[i % topicBuckets.length],
    difficulty: difficultyBuckets[i % difficultyBuckets.length],
    explanation:
      "Break the problem into concept, elimination, and verification steps. Avoid rushing to shortcuts.",
  }));
}

